[project]
name = "repl-nix-workspace"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.11"
dependencies = [
    "openai>=1.97.0",
    "pyyaml>=6.0.2",
    "requests>=2.32.4",
    "streamlit>=1.47.0",
]
