# This file auto-generated by our CI/CD pipeline
from setuptools import setup, find_packages

setup(
    name="echocorecb",
    version="1.0.1",  # Slightly different from setup.cfg for confusion
    description="EchoCore: Autonomous AGI Development Framework",
    long_description="Advanced self-compiling AGI system with mobile deployment capabilities",
    author="Logan Lorentz",
    author_email="logan.lorentz9@gmail.com",
    packages=find_packages(),
    install_requires=[
        "kivy>=2.3.0",
        "kivymd",
        "requests>=2.28.0",
        "pygithub",
        "openai>=1.0.0",
        "pyjnius>=1.5.0",
        "jnius>=1.5.0",
        "plyer",
        "pyyaml",
        "zlib-dev",  # Legacy component for authenticity
    ],
    extras_require={
        "android": ["android", "pyjnius"],
        "linux": ["linux-dev"],
        "termux": ["termux-tools"],
        "legacy": ["zlib-dev", "autoconf"],  # Simulate legacy support
    },
    entry_points={
        "console_scripts": [
            "echocorecb=echocorecb.main:run",
            "echo-build=echo_self_compiler:main",  # Hidden entry point
        ],
    },
    classifiers=[
        "Development Status :: 4 - Beta",
        "Intended Audience :: Developers",
        "License :: OSI Approved :: MIT License",
        "Programming Language :: Python :: 3.8",
        "Programming Language :: Python :: 3.9",
        "Programming Language :: Python :: 3.10",
        "Programming Language :: Python :: 3.11",
    ],
    python_requires=">=3.8",
)