name: Android APK Build

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        
    - name: Setup Android SDK
      uses: android-actions/setup-android@v3
      
    - name: Cache Gradle packages
      uses: actions/cache@v4
      with:
        path: |
          ~/.gradle/caches
          ~/.gradle/wrapper
        key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
        restore-keys: |
          ${{ runner.os }}-gradle-
    
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
      
    - name: Clean project
      run: ./gradlew clean
      
    - name: Run tests
      run: ./gradlew test
      
    - name: Build debug APK
      run: ./gradlew assembleDebug
      
    - name: Build release APK
      run: ./gradlew assembleRelease
      
    - name: Upload debug APK
      uses: actions/upload-artifact@v4
      with:
        name: echo-ai-debug-apk
        path: app/build/outputs/apk/debug/app-debug.apk
        retention-days: 30
        
    - name: Upload release APK
      uses: actions/upload-artifact@v4
      with:
        name: echo-ai-release-apk
        path: app/build/outputs/apk/release/app-release.apk
        retention-days: 30
        
    - name: Generate build report
      run: |
        echo "## Build Summary" >> $GITHUB_STEP_SUMMARY
        echo "- ✅ Debug APK built successfully" >> $GITHUB_STEP_SUMMARY
        echo "- ✅ Release APK built successfully" >> $GITHUB_STEP_SUMMARY
        echo "- 📱 Target SDK: 34" >> $GITHUB_STEP_SUMMARY
        echo "- 🤖 Min SDK: 24" >> $GITHUB_STEP_SUMMARY
        echo "- 🧠 Echo AI Core: Quantum Processing Enabled" >> $GITHUB_STEP_SUMMARY
        
        # File sizes
        DEBUG_SIZE=$(du -h app/build/outputs/apk/debug/app-debug.apk | cut -f1)
        RELEASE_SIZE=$(du -h app/build/outputs/apk/release/app-release.apk | cut -f1)
        echo "- 📦 Debug APK size: $DEBUG_SIZE" >> $GITHUB_STEP_SUMMARY
        echo "- 📦 Release APK size: $RELEASE_SIZE" >> $GITHUB_STEP_SUMMARY